name: CI - Solidity Library - installing, testing string utilities, uploading artifacts

# We run this test only for push events
on:
  push:
    branches: [main]

# Setup jobs
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Download the library code
      - uses: actions/checkout@v3

      # 2. Node.js setup
      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Hardhat works fine with this version

      # 3. Install the dependecies
      - name: Installing dependencies
        run: npm install

      # 4. Compile the project
      - name: Compiling project
        run: npx hardhat compile    

      # 5. Testing the string manipulation methods and making gas report
      - name: Testing methods and making gas report
        run: npx hardhat test
      - name: Upload Gas Report (click to download)
        uses: actions/upload-artifact@v3
        with:
          name: gas-report
          path: gas-report.txt

      # 5. Making test coverage report
      - name: Making test coverage report
        run: npx hardhat coverage            

      # 6. Saving the artifacts
      - name: Saving artifacts
        uses: actions/upload-artifact@v4
        with:
          name: contract-artifacts
          path: artifacts/
        if: success()
